version: '3'
services:
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    restart: always
    networks:
      - mdb-cs
    command: mongod --replSet rs0 --bind_ip_all --port 27017

  receiver:
    build: ./receiver
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo
    restart: always
    networks:
      - mdb-cs

  watcher:
    build: ./watcher
    depends_on:
      - mongo
      - initialize
    restart: always
    links:
      - mongo
    networks:
      - mdb-cs

  initialize:
    build:
      context: .
      dockerfile: init-mongo-rs.dockerfile
    depends_on:
      - mongo
    networks:
      - mdb-cs
    entrypoint: /bin/bash /init-entrypoint.sh

networks:
  mdb-cs:
